[package]
name = "docs_dupe_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6", features = ["ws"] }
tower-http = { version = "0.3", features = ["fs"] }
futures-util = "0.3"









